apiVersion: opentelemetry.io/v1alpha1
kind: AmazonCloudWatchAgent
metadata:
  name: opentelemetrycollector-as-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug]
